name: Generate Scan Summary

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create scan summary
        run: |
          mkdir -p summaries
          LAST=$(ls -t reports/nmap_report_*.txt | head -n 1)
          OUT="summaries/summary_$(date +'%Y%m%d%H%M%S').md"
          echo "# Nmap Summary - $(date)" > "$OUT"
          echo "" >> "$OUT"
          echo "**Último reporte:** $LAST" >> "$OUT"
          echo "" >> "$OUT"
          echo '```' >> "$OUT"
          tail -n 20 "$LAST" >> "$OUT"
          echo '```' >> "$OUT"

      - name: Commit summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add summaries/
          git diff --cached --quiet || git commit -m "Add scan summary $(date)"
          git push
