name: Generate Scan Summary

on:
  push:
    branches:
      - master

jobs:
  generate-summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Summary
      run: |
        # Your script to generate the summary
        echo "Generating summary..."
        mkdir -p summaries
        echo "Summary generated on $(date)" > summaries/summary_$(date +%Y%m%d%H%M%S).md

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add summaries/
        git commit -m "Add scan summary $(date)"
        git push origin HEAD:main
